<?xml version="1.0" encoding="UTF-8"?>
<!-- Generated by org.testng.reporters.JUnitXMLReporter -->
<testsuite hostname="RAJAT" ignored="0" name="Login Module" tests="8" failures="4" timestamp="28 Feb 2021 11:37:40 GMT" time="5.683" errors="0">
  <testcase name="loginTest" time="5.628" classname="listener.Demo1Fortestng">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at listener.Demo1Fortestng.loginTest(Demo1Fortestng.java:25)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- loginTest -->
  <testcase name="verifyTitle" time="0.0" classname="listener.Demo1Fortestng">
    <skipped/>
  </testcase> <!-- verifyTitle -->
  <testcase name="verifyAddition" time="0.001" classname="com.javabykiran.BasicTesting">
    <failure type="java.lang.AssertionError" message="expected [78] but found [23]">
      <![CDATA[java.lang.AssertionError: expected [78] but found [23]
	at com.javabykiran.BasicTesting.verifyAddition(BasicTesting.java:19)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyAddition -->
  <testcase name="verifyDivision" time="0.001" classname="com.javabykiran.BasicTesting">
    <failure type="java.lang.AssertionError" message="expected [23] but found [78]">
      <![CDATA[java.lang.AssertionError: expected [23] but found [78]
	at com.javabykiran.BasicTesting.verifyDivision(BasicTesting.java:37)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- verifyDivision -->
  <testcase name="verifyMultiplication" time="0.0" classname="com.javabykiran.BasicTesting"/>
  <testcase name="verifySubtraction" time="0.001" classname="com.javabykiran.BasicTesting"/>
  <testcase name="test03" time="0.001" classname="listener.Demo1Fortestng">
    <failure type="java.lang.AssertionError" message="expected [1] but found [0]">
      <![CDATA[java.lang.AssertionError: expected [1] but found [0]
	at listener.Demo1Fortestng.test03(Demo1Fortestng.java:36)
... Removed 31 stack frames]]>
    </failure>
  </testcase> <!-- test03 -->
  <testcase name="test04" time="0.0" classname="listener.Demo1Fortestng"/>
</testsuite> <!-- Login Module -->
